In [2]:
import pandas as pd
import os

pd.set_option('max_colwidth', None)

PATH = os.getcwd()

In [108]:
df = pd.read_excel(PATH + "/Data_ChatHDSD.xlsx", sheet_name="Sheet1")
# df.head(5)

In [112]:
import html
# df["RESPONSE"] = df["RESPONSE"].apply(html.unescape)
df['RESPONSE'] = df['RESPONSE'].apply(lambda x: html.unescape(x) if isinstance(x, str) else x)
df['EXAMPLE'] = df['EXAMPLE'].apply(lambda x: html.unescape(x) if isinstance(x, str) else x)

In [110]:
df['RESPONSE'] = df['RESPONSE'].str.replace("\"", "'")
df['RESPONSE'] = df['RESPONSE'].str.replace("*", "+")

In [111]:
# Write Domain Response YML:
f1 = open(PATH + "/domain_yml_respon.txt", "w")

for i, utter in enumerate(df["STT"]):
    if not df["STT"].isnull()[i]:
        line = "  utter_" + str(int(utter)) + ":\n" + "    - text: " + "\"" + df["RESPONSE"][i] + "\"" + "\n" + "\n"
        f1.write(line)
        
    # else:
    #     line = "    - text: \"" + str(df["RESPONSE"][i]) + "\"\n"
    #     f1.write(line)

f1.close()

In [116]:
# Write NLU YML:
f1 = open(PATH + "/nlu_yml.txt", "w")
f2 = open(PATH  + "/domain_yml_intent.txt", "w")
f2.write("intents:\n")

for i, intent in enumerate(df["STT"]):
    if not df["STT"].isnull()[i]:
        # print(intent)
        line = "\n- intent: " + "intent_" + str(int(intent)) + "\n" + "  examples: |\n" + "    - " + str(df["EXAMPLE"][i]) + "\n"
        f1.write(line)
        line = "- " + "intent_" + str(int(intent)) + "\n"
        f2.write(line)
        
    else:
        line = "    - " + str(df["EXAMPLE"][i]) + "\n"
        f1.write(line)

f1.close()
f2.close()

In [21]:
# df = pd.read_excel("C:\Isofh\Rasa\ConvertExceltoNLU\Kịch bản tương tác_VN.xlsx", sheet_name="Template Response")
# df.head(5)

In [19]:
# Write Stories YML:
f1 = open("C:/Isofh/Rasa/ConvertExceltoNLU/Stories.txt", "w")

for i, stt in enumerate(df["STT"]):
    if not df["STT"].isnull()[i]:
        line = "\n- story: " + "story " + str(int(float(str(df["STT"][i])))) + "\n  steps:"
        f1.write(line)
        if "intent" in str(df["Stories"][i]):
            line = "\n  - intent: " + str(df["Stories"][i]) 
        else:
            line = "\n  - action: " + str(df["Stories"][i]) 

        f1.write(line)
        
    else:
        if "intent" in str(df["Stories"][i]):
            line = "\n  - intent: " + str(df["Stories"][i]) 
        else:
            line = "\n  - action: " + str(df["Stories"][i]) 

        f1.write(line)

f1.close()

In [28]:
# df = pd.read_excel("C:\Isofh\Rasa\ConvertExceltoNLU\Kịch bản tương tác_VN.xlsx", sheet_name="Template Rules")
# df.head(5)

In [35]:
# Write Rules YML:
f1 = open(PATH + "/rules_yml.txt", "w")

for i, stt in enumerate(df["STT"]):
    if not df["STT"].isnull()[i]:
        line = "\n- rule: " + "rule_" + str(int(stt)) + "\n  steps:"
        f1.write(line)
        line = "\n  - intent: intent_" + str(int(stt)) 
        f1.write(line)
        line = "\n  - action: utter_" + str(int(stt)) + "\n"
        f1.write(line)

    # else:
    #     if "intent" in str(df["Rules"][i]):
    #         line = "\n      - intent: " + str(df["Rules"][i]) 
    #     else:
    #         line = "\n      - action: " + str(df["Rules"][i]) 

    #     f1.write(line)

f1.close()

In [22]:
df = pd.read_excel("C:\Isofh\Rasa\ConvertExceltoNLU\Kịch bản tương tác_VN.xlsx", sheet_name="Template Stories_Tuấn")
df.head(5)

   STT                  Stories  Rules
0  1.0  intent_am_dao_bi_ra_mau    NaN
1  NaN      utter_co_thai_khong    NaN
2  NaN                 utter_co    NaN
3  NaN              utter_khong    NaN
4  NaN                intent_co    NaN

In [23]:
df1 = pd.read_excel("C:\Isofh\Rasa\ConvertExceltoNLU\Kịch bản tương tác_VN.xlsx", sheet_name="Template Intent")
df1.head(5)

,TOPIC,STT,INTENT,EXAMPLE,NOTE,Note: - Với mỗi intent cố gắng tạo ít nhất 2 example. Nếu không tìm được câu khác có thể lấy câu đầu tiên rồi sửa một vài từ.\n - Hiện làm những câu đơn giản trước. Những câu có liên quan đến chỉ số để đánh giá cần định nghĩa rõ sau.\n
0,âm đạo bị ra máu,NaN,intent_am_dao_bi_ra_mau,Em đang gặp tình trạng âm đạo bị ra máu màu nâu đỏ,NaN,NaN
1,NaN,NaN,NaN,âm đạo ra máu,NaN,NaN
2,NaN,NaN,intent_khong,Không,NaN,NaN
3,NaN,NaN,NaN,Không,NaN,NaN
4,NaN,NaN,intent_co,Có,NaN,NaN

In [24]:
# Write Stories YML:
f1 = open("C:/Isofh/Rasa/ConvertExceltoNLU/test_stories.txt", "w")

for i, stt in enumerate(df["STT"]):
    if not df["STT"].isnull()[i]:
        line = "\n- story: " + "story " + str(int(float(str(df["STT"][i])))) + "\n  steps:"
        f1.write(line)
        if "intent" in str(df["Stories"][i]):
            line = "\n  - user: |"
            f1.write(line)
            line = "\n      " + df1.loc[df1['INTENT'] == str(df["Stories"][i])]['EXAMPLE'].to_string(index=False)
            f1.write(line)
            line = "\n    intent: " + str(df["Stories"][i]) 
        else:
            line = "\n  - action: " + str(df["Stories"][i]) 

        f1.write(line)
        
    else:
        if "intent" in str(df["Stories"][i]):
            line = "\n  - user: |"
            f1.write(line)
            line = "\n      " + df1.loc[df1['INTENT'] == str(df["Stories"][i])]['EXAMPLE'].to_string(index=False)
            f1.write(line)    
            line = "\n    intent: " + str(df["Stories"][i]) 
        else:
            line = "\n  - action: " + str(df["Stories"][i]) 

        f1.write(line)

f1.close()